input-field {
	monitor =
	fade_on_empty = false
	inner_color = rgba(173,83,137,1.0)
	outer_color = rgba(76,0,153,1.0)
	font_color = rgba(51,0,102,1.0)
}

background {
	path = /home/bogdan/.wallpapers/bg.png
	blur_passes = 1
	blur_size = 5
}
